name: Release Danger-Kotlin package

on:
  push:
    tags-ignore: 
      - 'sdk_*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Export tag version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    
    - name: Docker Login
      run: echo $PACKAGES_WRITE_TOKEN | docker login ghcr.io -u $USERNAME --password-stdin
      env:
        PACKAGES_WRITE_TOKEN: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
        USERNAME: ${{ secrets.DOCKER_GITHUB_USERNAME }}

    - name: Docker Build
      run: docker build -t ghcr.io/danger/danger-kotlin:$VERSION .

    - name: Deploy
      run: docker push ghcr.io/danger/danger-kotlin:$VERSION
